# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#

substitutions:
  _JFROG_SERVER_NAME: <servername>.jfrog.io
  _JFROG_USER: <name>@<yourcompany>.com
  _JFROG_API_KEY: <api key>
  _JFROG_REPO_NAME: clouddays
  _JFROG_CLI_VERSION: 2.11.0
  
steps:
# Build the Cloud Builder Image that includes JFrog CLI
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=gcr.io/cloud-builders/npm:node-14.10.0'
  - '--tag=gcr.io/$PROJECT_ID/npm/${_JFROG_CLI_VERSION}'
  - '--tag=${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
  - '.'
  wait_for: ['-']

# Tag a default builder version.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
  - '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'login'
  - '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/java-app'
  - '-u'
  - '${_JFROG_USER}'
  - '-p'
  - '${_JFROG_API_KEY}'

images:
- '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
- '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli'
tags: ['cloud-builders-community']
